### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by java-boy** [carloslancha/spaceship-react#1]
I could not find any source code of the presentation here.
Can I ask you to push that?
Thanks in advance.

**Comment by carloslancha** [comment]
Hi @java-boy you can find the source code in the different branches, separated by step followed during the presentation, from 01-Create-App to 08-Localization, all of them developed and tested with Liferay 7.3.x.

Thx

**Comment by java-boy** [comment]
Hi @carloslancha, Thanks a lot for your response 👍 , 
I cloned the 08-Localization branch and after running `npm i `command, I run `npm run start`,  and I get the following error :

E:\liferayTest\react-app\spaceship-react>npm start run

> spaceship@0.1.0 start E:\liferayTest\react-app\spaceship-react
> lnbs-start "run"

E:\liferayTest\react-app\spaceship-react\.webpack\webpack.config.js:18
        plugins: [new require('copy-webpack-plugin')(['../assets'])],
                                                                                ^

TypeError: Class constructor CopyPlugin cannot be invoked without 'new'
    at Object.<anonymous> (E:\liferayTest\react-app\spaceship-react\.webpack\webpack.config.js:18:46)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at WEBPACK_OPTIONS (E:\liferayTest\react-app\spaceship-react\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (E:\liferayTest\react-app\spaceship-react\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at E:\liferayTest\react-app\spaceship-react\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (E:\liferayTest\react-app\spaceship-react\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (E:\liferayTest\react-app\spaceship-react\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)

My nodejs version is 14.9.0
